Add Sorting functionality within the chapter
BookStackApp/BookStack pull request #3060
Opened 2021-11-18 11:14 UTC by Shubhamt04

- Able to sort the sort the chapter based on sorting filter.
- Had some issue with updating sorting pattern, tried to fix it but couldn't fix it.
@ssddanbrown I'm kinda stuck now. So, can you suggest me an approach to save sorting pattern for chapter?

2021-11-18 12:21 UTC, ssddanbrown commented
> I'm kinda stuck now. So, can you suggest me an approach to save sorting pattern for chapter?

You should be able to re-use the existing `applySortUpdates` function instead of re-creating a new chapter-specific one for saving the new sort order. You're going to need to update the `getChaptersInvolvedInSort` function you got to select the correct chapter references out of the sortMap.

2021-11-24 18:08 UTC, ssddanbrown requested changes
Thanks for this @Shubhamt04. Looks like it's coming together.
Got a few changes to request, Most of them relatively quick and minor.

2021-11-24 18:08 UTC, ssddanbrown commented on resources/js/components/chapter-sort.js
> +    },
These sort types don't appear to have any purpose.

2021-11-24 18:08 UTC, ssddanbrown commented on resources/js/components/chapter-sort.js
> +export default ChapterSort;
This entire class shares a massive amount of logic with the `book-sort.js` file. Could this not instead be made into a generic `content-sort.js` file? I just don't want duplicate classess/functions to maintain if possible.

2021-11-24 18:08 UTC, ssddanbrown commented on resources/lang/en/entities.php
> +    'chapters_sort_updated' => 'Sort by Updated Date',
Can just use the existing book-based string instead of creating new translation strings with the same content.

2021-11-24 18:08 UTC, ssddanbrown commented on resources/lang/en/entities.php
> +    'chapters_sort_pages_last' => 'Pages Last',
Should be no need for these strings.

2021-11-24 18:08 UTC, ssddanbrown commented on resources/views/chapters/parts/sort-box.blade.php
> +        <a href="#" data-sort="pagesLast" class="button outline small">{{ trans('entities.chapters_sort_pages_last') }}</a>
As per other comments, Don't think there's a purpose for these.

2021-11-25 07:29 UTC, Shubhamt04 commented
> Thanks for this @Shubhamt04. Looks like it's coming together. Got a few changes to request, Most of them relatively quick and minor.

Sure @ssddanbrown , Will work on the suggested changes.

2022-02-08 15:41 UTC, ssddanbrown commented
Since there's not been much recent active progress on this I'm going to close this off.
Feel free to re-open though if this could be implemented with the above comments addressed. 
In addition, I think there's since been some further changes in the core codebase which would need incorporating for this work if proceeding (A fair amount of extra permission checks).
Either way, thanks for your efforts so far @Shubhamt04 and for your offer of this code.

2022-02-08 15:41 UTC, closed without merging