Multiple LDAP servers
BookStackApp/BookStack pull request #3742
Opened 2022-09-21 12:30 UTC by Khazhinov

Hello!
I want to express my gratitude, because Bookstack has become an indispensable tool for me in my work!
But in order to get a failover option for Bookstack service on a domain network, I needed to be able to specify multiple domain controller addresses.
I propose a simple implementation of this feature.

Just specify the ```LDAP_SERVER``` variable in the .env file in the format: ```dc1.domain.local:389;dc2.domain.local:389```

2022-09-22 14:03 UTC, ssddanbrown requested changes
Thank you very much for offering this PR @Khazhinov!

I've performed a quick review of the submitted updates, and have picked up some changes that would be good to action, in the interest of ensuring this all works as expected for different options, and to ensure we are not duplicating code to keep things maintainable.

It would also be good to add some testing to cover this logic.

Don't hesitate to let me know if you have any issues and questions in regards to my comments, if needed I could pick this up and address the comments if you're unable to progress.

2022-09-22 14:03 UTC, ssddanbrown commented on .env.example.complete
> +# If you need to use multiple addresses, separate them with a semicolon. Ex: dc1.domain.local:389;dc2.domain.local:389
Please can you remove this comment, this would be something I'd document on our docs website link referenced above.

2022-09-22 14:03 UTC, ssddanbrown commented on app/Auth/Access/LdapService.php
> +        if (array_key_exists('hosts', $serverDetails)) {
Please could this logic be aligned so we don't have seperate logic (via this `if` statement) for single vs mulitple hosts.
See my comment for the `parseServerString` function for more detail.

2022-09-22 14:03 UTC, ssddanbrown commented on app/Auth/Access/LdapService.php
> +                throw new LdapException(trans('errors.ldap_cannot_connect'));
This error handling would hide indication of TLS issues (as thrown on line 239).
At the very least, it would be good to emit the last received exception message.

2022-09-22 14:03 UTC, ssddanbrown commented on app/Auth/Access/LdapService.php
> +        if (count($explodedServerString) > 1) {
This change currently puts the old logic into the `else` of this condition, while adding all new logic within an `if` condition, but much of this logic is exactly the same. This also means there's two different return structures to consider.

Please could this logic be aligned so we don't have separate logic in an outer `if` statement like this?
You simplify the return type to always by an array of `['host' => $hostName, 'port' => $ldapPort]` pairs.

2022-09-22 14:03 UTC, ssddanbrown commented on app/Auth/Access/LdapService.php
> +                    return ['host' => $serverString, 'port' => 389];
The return here means that multi-hosts won't be handled if they include a protocol.

2022-09-30 06:55 UTC, Khazhinov commented
Thanks for the detailed review! Posted an update

2022-10-04 11:20 UTC, ssddanbrown commented
Thanks @Khazhinov, 
From a quick can this is looking real good now. 
Have assigned to be reviewed and merged as part of the next release.

BTW, Don't worry about keeping this branch up-to-date with `development`, I can merge it in once required.

2022-10-16 22:00 UTC, ssddanbrown commented
Just been reviewing this, [adding tests and little refactoring](https://github.com/BookStackApp/BookStack/compare/ldap_host_failover), but while doing that I found this implementation only works if `LDAP_START_TLS=true` since otherwise a connection is not attempted until later. Although a recommended option, I'm wouldn't be happy with having that caveat for this addition. 

We could do some form of connection test request, but think that would be a bit hacky. 
We always bind after connection creation, but just in a few different ways, so the failover logic could wrap `(connect + bind)` instead of just `(connect)`. I'll need to spend a little time to find a clean approach without affecting/risking existing logic.

Going to unassign this from next feature release though as I don't want it delaying anything.

2022-10-17 17:18 UTC, ssddanbrown commented
Continued in #3784, this will remain open until #3784 is merged.

2022-11-25 18:06 UTC, ssddanbrown commented
Sorry to say I'm giving up on this for now and will hence close this off, as I have done for #3784.
My attempts to make this fit have just used a lot of time and ended up with an unreasonable amount of code surface area growth relative to the benefit, which would be a feature that really has had quite minimal demand. 
Feel like it needs a new approach but I'm out of patience for this.

To be honest, I would have advised against creating a PR if asked up-front, due to the little demand for this, but the changes in the original PR looked minimal so I thought it would be a quick addition, but I've probably spent over 6 hours on this now and don't want to spend any more. Can always come back to it in the future.

Thanks @Khazhinov for offering the original PR though.

2022-11-25 18:06 UTC, closed without merging

2022-11-25 18:52 UTC, Khazhinov commented
I don't understand how domain authentication can be without fallback address features.
Thank you for taking the time for this.
Hope you can solve this problem in the future.